### ISSUE TITLE
Feature Request: Disable on Mobile option?

### ISSUE THREAD

**Issue by samumist** [qwerty1829/adapt-introjs#4]
hello @simondate 
I'm applying the adapt-intro on a hotspot menu. The extension works great on desktop view. When I switch to mobile view, the hotspot menu switch to a boxmenu which renders the intro steps in the wrong places.

I'm wondering if you could add an option to turn this off on mobile view? like an option to hide the icon?

Many thanks!

**Comment by samumist** [comment]
I was able to use the css to hide the icon on mobile view with the following code.
```less
.size-small .navigation > .navigation-inner .navigation-intro { display: none !important; } 
```
